services:
  # DB同期ワーカー
  db-sync:
    build: .
    command: python -m app.tasks.db_sync_worker
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:cCYEcPkgQLhDrATixKqLHeWRyJdpOhQt@maglev.proxy.rlwy.net:25873/railway
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped 